/*! Module03StructuredExceptionHandling 2017-07-25 */

function UserException(o){this.message=o,this.name="UserException"}function flipOfBoom(){if(Math.floor(2*Math.random()))throw new UserException("Boom!!");return"Survived!"}console.log("FileName:  Complete/01StructuredExceptionHandling.js"),console.log(""),console.log("****************************************************************"),console.log("Topic:  Structured Exception Handling"),console.log("****************************************************************"),UserException.prototype.toString=function(){return this.name+': "'+this.message+'"'};try{console.log("try"),console.log(flipOfBoom())}catch(o){console.log("catch(e)"),console.log(o),console.log(o.toString())}finally{console.log("finally")}